name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.3
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.1
  firebase_auth: ^5.4.1
  cloud_functions: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0
  shared_preferences: ^2.2.2


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

 