// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpBxXLFBeaIgUx0AsZXR9FlYig9EVIu2Y',
    appId: '1:644093852517:web:2dfb5bb6240792b8c87f8c',
    messagingSenderId: '644093852517',
    projectId: 'testfirebase1-9d96c',
    authDomain: 'testfirebase1-9d96c.firebaseapp.com',
    storageBucket: 'testfirebase1-9d96c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDimlkLA-HZGo1BVkTwzSXedJkBKMnS1rs',
    appId: '1:644093852517:android:9da189b0c6c45ebfc87f8c',
    messagingSenderId: '644093852517',
    projectId: 'testfirebase1-9d96c',
    storageBucket: 'testfirebase1-9d96c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKliS-Pd7d-9KhicqJRm1dQAcee80zcV4',
    appId: '1:644093852517:ios:f6db87768301641cc87f8c',
    messagingSenderId: '644093852517',
    projectId: 'testfirebase1-9d96c',
    storageBucket: 'testfirebase1-9d96c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKliS-Pd7d-9KhicqJRm1dQAcee80zcV4',
    appId: '1:644093852517:ios:f6db87768301641cc87f8c',
    messagingSenderId: '644093852517',
    projectId: 'testfirebase1-9d96c',
    storageBucket: 'testfirebase1-9d96c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpBxXLFBeaIgUx0AsZXR9FlYig9EVIu2Y',
    appId: '1:644093852517:web:26d8b2fb89e5b5b5c87f8c',
    messagingSenderId: '644093852517',
    projectId: 'testfirebase1-9d96c',
    authDomain: 'testfirebase1-9d96c.firebaseapp.com',
    storageBucket: 'testfirebase1-9d96c.firebasestorage.app',
  );

}